# Page settings

baseURL = "https://zhuchance.github.io/"
languageCode = "zh-CN"
title = "Devops k8s go vue"
theme = "hugo-business-frontpage-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "北冥鱼"
    description = "记录 分享 学习 提升"
    # date_format = "2020-02-19"






    [params.navbar]
        name = "Start Bootstrap"
        url = "https://zhuchance.github.io/"

        [[params.navbar.nav]]
        current = true
        name = "Home"
        url = "#"
        [[params.navbar.nav]]
        name = "Golang"
        url = "#"
        [[params.navbar.nav]]
        name = "Kubernetes"
        url = "#"
        [[params.navbar.nav]]
        name = "About"
        url = "#"
        [[params.navbar.nav]]
        name = "Python"
        url = "#"
        [[params.navbar.nav]]
        name = "Network"
        url = "#"
        [[params.navbar.nav]]
        name = "Archive"
        url = "#"






    [params.header]
        name = "Hi 朋友,欢迎光临"
        tagline = "使用Hago技术用来记录分享一些工作学习文档"






    [params.summary]
        url = "#"

        [params.summary.description]

        [[params.summary.description.items]]
        description = "我是一个热爱生活，热爱工作的90后，目前在南京就职于京东五星电器，是一名容器技术爱好者。"
        #[[params.summary.description.items]]
        #description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum."


        [params.summary.contact]
        name = "北冥鱼"
        address1 = "南京"
        address2 = "鼓楼区"
        phone = "111111111111"
        email = "couchance@gmail.com"






    [params.projects]

        [[params.projects.sections]]
        # title = "Section 1"

        [[params.projects.sections.rows]]
        # title = "Section 1, Row 1"

        [[params.projects.sections.rows.items]]
        title = "MetalLB-local-loadbalancer"
        description = "用来给services暴露IP出来，规划一个集群同网段的IP出来，使用的时候services不能删除，这样方便对接公网的Load balance的nginx，为了让k8s集群和旧的swarm集群能同时提供服务。"
        url = "#"
        # image = "image.png"
        [[params.projects.sections.rows.items]]
        title = "deployment jenkins on k8s cluster"
        description = "使用Jenkins做CI CD"
        url = "#"
        # image = "image.png"
        [[params.projects.sections.rows.items]]
        title = "Harbor"
        description = "s使用Harbor做镜像仓库"
        url = "#"
        # image = "image.png"

        # [[params.projects.sections.rows]]
        # # title = "Section 1, Row 2"

        # [[params.projects.sections.rows.items]]
        # title = "Card title 4"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        # url = "#"
        # # image = "image.png"
        # [[params.projects.sections.rows.items]]
        # title = "Card title 5"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
        # url = "#"
        # # image = "image.png"


        # [[params.projects.sections]]
        # # title = "Section 2"

        # [[params.projects.sections.rows]]
        # # title = "Section 2, Row 1"

        # [[params.projects.sections.rows.items]]
        # title = "Card title 1"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        # url = "#"
        # # image = "image.png"
        # [[params.projects.sections.rows.items]]
        # title = "Card title 2"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
        # url = "#"
        # # image = "image.png"
        # [[params.projects.sections.rows.items]]
        # title = "Card title 3"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque."
        # url = "#"
        # # image = "image.png"

        # [[params.projects.sections.rows]]
        # # title = "Section 2, Row 2"

        # [[params.projects.sections.rows.items]]
        # title = "Card title 4"
        # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        # url = "#"
        # # image = "image.png"






    [params.footer]
        copyright = "北冥鱼"



